steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--rm', '--privileged', 'docker/binfmt:latest']
  id: 'initialize-qemu'
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'create', '--name', 'mybuilder']
  id: 'create-builder'
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'use', 'mybuilder']
  id: 'select-builder'
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'inspect', '--bootstrap']
  id: 'show-target-build-platforms'
- name: gcr.io/cloud-builders/docker
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', '--push', '-t', 'gcr.io/$PROJECT_ID/docker-aws-arm64:latest', '.']

# Print version information.
- name: gcr.io/$PROJECT_ID/docker-aws-arm64
  args: ['--version']

options:
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'
substitutions:
  _DOCKER_BUILDX_PLATFORMS: 'linux/arm64'